package view;

import controller.AgendaController;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Gabriel Braga
 */
public class Agenda extends javax.swing.JFrame {

    private final AgendaController controller;

    public Agenda() {
        this.setResizable(false);
        initComponents();
        controller = new AgendaController(this);
        iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        campo_id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campo_cliente = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        campo_servico = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        campo_valor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        campo_data = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        campo_hora = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campo_observacao = new javax.swing.JTextArea();
        btn_agendar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela_agendamentos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));

        campo_id.setBackground(new java.awt.Color(255, 255, 255));
        campo_id.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        campo_id.setForeground(new java.awt.Color(0, 0, 0));
        campo_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_idActionPerformed(evt);
            }
        });
        getContentPane().add(campo_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 400, 40));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cliente:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        campo_cliente.setBackground(new java.awt.Color(255, 255, 255));
        campo_cliente.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        campo_cliente.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(campo_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 400, 40));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Serviço:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        campo_servico.setBackground(new java.awt.Color(255, 255, 255));
        campo_servico.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        campo_servico.setForeground(new java.awt.Color(0, 0, 0));
        campo_servico.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                campo_servicoItemStateChanged(evt);
            }
        });
        getContentPane().add(campo_servico, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 400, 40));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Valor (R$):");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, -1));

        campo_valor.setBackground(new java.awt.Color(255, 255, 255));
        campo_valor.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        campo_valor.setForeground(new java.awt.Color(0, 0, 0));
        campo_valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_valorActionPerformed(evt);
            }
        });
        getContentPane().add(campo_valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 400, 40));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Data:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, -1, -1));

        campo_data.setBackground(new java.awt.Color(255, 255, 255));
        campo_data.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        campo_data.setForeground(new java.awt.Color(0, 0, 0));
        campo_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_dataActionPerformed(evt);
            }
        });
        getContentPane().add(campo_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 400, 40));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Hora:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, -1, -1));

        campo_hora.setBackground(new java.awt.Color(255, 255, 255));
        campo_hora.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        campo_hora.setForeground(new java.awt.Color(0, 0, 0));
        campo_hora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_horaActionPerformed(evt);
            }
        });
        getContentPane().add(campo_hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, 400, 40));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Observação:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, -1, -1));

        campo_observacao.setBackground(new java.awt.Color(255, 255, 255));
        campo_observacao.setColumns(20);
        campo_observacao.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        campo_observacao.setForeground(new java.awt.Color(0, 0, 0));
        campo_observacao.setRows(5);
        jScrollPane1.setViewportView(campo_observacao);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, 480, 280));

        btn_agendar.setBackground(new java.awt.Color(102, 255, 102));
        btn_agendar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_agendar.setForeground(new java.awt.Color(0, 0, 0));
        btn_agendar.setText("Agendar");
        btn_agendar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_agendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agendarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_agendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 460, 480, 40));

        tabela_agendamentos.setBackground(new java.awt.Color(255, 255, 255));
        tabela_agendamentos.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        tabela_agendamentos.setForeground(new java.awt.Color(0, 0, 0));
        tabela_agendamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cliente", "Serviço", "Valor (R$)", "Data", "Hora", "Observação"
            }
        ));
        jScrollPane2.setViewportView(tabela_agendamentos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 540, 920, 320));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/AgendaFundo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campo_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_idActionPerformed

    private void campo_valorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_valorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_valorActionPerformed

    private void campo_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_dataActionPerformed

    private void campo_horaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_horaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_horaActionPerformed

    private void btn_agendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agendarActionPerformed
        controller.agendar();
    }//GEN-LAST:event_btn_agendarActionPerformed

    private void campo_servicoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_campo_servicoItemStateChanged
        controller.atualizar_campo_valor();
    }//GEN-LAST:event_campo_servicoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agenda().setVisible(true);
            }
        });
    }

    private void iniciar() {
        controller.atualizar_tabela();
        controller.atualizar_campo_cliente();
        controller.atualizar_campo_servico();
        controller.atualizar_campo_valor();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agendar;
    private javax.swing.JComboBox<String> campo_cliente;
    private javax.swing.JTextField campo_data;
    private javax.swing.JTextField campo_hora;
    private javax.swing.JTextField campo_id;
    private javax.swing.JTextArea campo_observacao;
    private javax.swing.JComboBox<String> campo_servico;
    private javax.swing.JTextField campo_valor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabela_agendamentos;
    // End of variables declaration//GEN-END:variables

    public JButton getBtn_agendar() {
        return btn_agendar;
    }

    public void setBtn_agendar(JButton btn_agendar) {
        this.btn_agendar = btn_agendar;
    }

    public JComboBox<String> getCampo_cliente() {
        return campo_cliente;
    }

    public void setCampo_cliente(JComboBox<String> campo_cliente) {
        this.campo_cliente = campo_cliente;
    }

    public JTextField getCampo_data() {
        return campo_data;
    }

    public void setCampo_data(JTextField campo_data) {
        this.campo_data = campo_data;
    }

    public JTextField getCampo_hora() {
        return campo_hora;
    }

    public void setCampo_hora(JTextField campo_hora) {
        this.campo_hora = campo_hora;
    }

    public JTextField getCampo_id() {
        return campo_id;
    }

    public void setCampo_id(JTextField campo_id) {
        this.campo_id = campo_id;
    }

    public JTextArea getCampo_observacao() {
        return campo_observacao;
    }

    public void setCampo_observacao(JTextArea campo_observacao) {
        this.campo_observacao = campo_observacao;
    }

    public JComboBox<String> getCampo_servico() {
        return campo_servico;
    }

    public void setCampo_servico(JComboBox<String> campo_servico) {
        this.campo_servico = campo_servico;
    }

    public JTextField getCampo_valor() {
        return campo_valor;
    }

    public void setCampo_valor(JTextField campo_valor) {
        this.campo_valor = campo_valor;
    }

    public JTable getTabela_agendamentos() {
        return tabela_agendamentos;
    }

    public void setTabela_agendamentos(JTable tabela_agendamentos) {
        this.tabela_agendamentos = tabela_agendamentos;
    }

    public void exibir_mesagem(String mensagem) {
        JOptionPane.showMessageDialog(null, mensagem, "AVISO", JOptionPane.INFORMATION_MESSAGE);
    }

}
