package view;

import controller.MenuPrincipalController;

/**
 *
 * @author Gabriel Braga
 */
public class MenuPrincipal extends javax.swing.JFrame {

    private final MenuPrincipalController controller;

    public MenuPrincipal() {
        this.setExtendedState(MAXIMIZED_BOTH);
        initComponents();
        controller = new MenuPrincipalController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_item_cadastro_cliente = new javax.swing.JMenuItem();
        menu_item_cadastro_servico = new javax.swing.JMenuItem();
        menu_item_cadastro_usuario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menu_item_agenda = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/fundo-MenuPrincipal.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 1080));

        jMenu1.setText("Cadastro");

        menu_item_cadastro_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/cliente-icon.png"))); // NOI18N
        menu_item_cadastro_cliente.setText("Cliente");
        jMenu1.add(menu_item_cadastro_cliente);

        menu_item_cadastro_servico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/tesoura-icon.png"))); // NOI18N
        menu_item_cadastro_servico.setText("Serviço");
        menu_item_cadastro_servico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_cadastro_servicoActionPerformed(evt);
            }
        });
        jMenu1.add(menu_item_cadastro_servico);

        menu_item_cadastro_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/icons/usuario-icon.png"))); // NOI18N
        menu_item_cadastro_usuario.setText("Usuário");
        menu_item_cadastro_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_cadastro_usuarioActionPerformed(evt);
            }
        });
        jMenu1.add(menu_item_cadastro_usuario);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Operação");

        menu_item_agenda.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gabriel Braga\\Documents\\PROJETOS\\barbershop\\BarberShop\\src\\view\\imagens\\icons\\agenda-icon.png")); // NOI18N
        menu_item_agenda.setText("Agenda");
        menu_item_agenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_agendaActionPerformed(evt);
            }
        });
        jMenu2.add(menu_item_agenda);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Relatório");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_item_cadastro_servicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_cadastro_servicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_item_cadastro_servicoActionPerformed

    private void menu_item_cadastro_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_cadastro_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_item_cadastro_usuarioActionPerformed

    private void menu_item_agendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_agendaActionPerformed
        controller.navegar_para_agenda();
    }//GEN-LAST:event_menu_item_agendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MenuPrincipal menuPrincipal = new MenuPrincipal();
                menuPrincipal.setExtendedState(MAXIMIZED_BOTH);
                menuPrincipal.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menu_item_agenda;
    private javax.swing.JMenuItem menu_item_cadastro_cliente;
    private javax.swing.JMenuItem menu_item_cadastro_servico;
    private javax.swing.JMenuItem menu_item_cadastro_usuario;
    // End of variables declaration//GEN-END:variables
}
